# Generated by Django 3.0.5 on 2021-05-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.FloatField(max_length=12)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=300)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teammate.UserModel')),
            ],
        ),
    ]
